![imagen](./img/ejercicios.png)

In [1]:
import numpy as np # HACER ESTOS EJERCICIOS, ANALIZAR UTILIZAR "PANDAS"


## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [17]:
my_array = np.arange(10)
print(my_array[::-2]) # :: IMPRIME TODOS LOS DATOS 
                       # -2 EL 2 HACE QUE SE IMPRIMA UNO POR MEDIO, Y EL (-) HACE QUE SE IMPRIMAN DE ATRAS PARA ADELANTE 

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [27]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [29]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [41]:
matriz = np.arange(1, 21).reshape(4, 5) 
#print(matriz)
'''la matriz es: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

'''

# invertir la matriz totalmente  
matriz_invertida = np.flip(matriz, axis=0) # con axis = 0, lo único que hace es cambiar el orden de las filas de la matriz 
                                            # la funcion "flip() invierte la matriz", ya sea en un eje o totalmente 
''' muestra el resultado: 
[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]'''
matriz_invertida = np.flip(matriz_invertida, axis=1) # con axis = 1, cambia las filas y las columnas de la matriz, es decir, la cambia totalmente 
''' la linea de arriba muestra el resultado: 
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]'''
print(matriz_invertida) 

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [42]:
matriz_datos = np.arange(1, 21).reshape(4, 5) 

matriz_resultado = matriz_datos[:2, :2] # ESTE COMANDO LO QUE ME DICE ES QUE DE LA MATRIZ ORIGINAL, VOY A EXTRAER LOS ELEMENTOS QUE ABARCAN EN EL EJE X EN LA POSICION 1º Y 2º
                                   # Y EN EL EJE Y LOS ELEMENTOS QUE ESTAN INCLUIDOS DESDE LAS POSICIONES 1º Y 2º, ES COMO HACER UNA VENTANA DE SELECCION CON EL RATON CON ESOS RANGOS DE AMPLITUD  
print(matriz_resultado)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [95]:
matriz_datos = np.arange(1, 21).reshape(4, 5)
matriz_resultado = matriz_datos[[0, 2], [0, 2, 4]]
print(matriz_resultado)

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [68]:
matriz_datos = np.arange(1, 21).reshape(4, 5)
matriz_resultado = matriz_datos[:3, ::-1]

print(matriz_resultado)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [70]:
# SOLUCION 1

x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

filtro_resultado = x[x == "Loro"] # LE ASIGNO A LA VARIABLE RESULTADO DIRECTAMENTE LA CONDICION PARA ESCOGER LOS ELEMENTOS 
print(filtro_resultado)

['Loro' 'Loro']


In [72]:
# SOLUCION 2 

x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

indices = np.where(x == "Loro") # UTILIZA LA FUNCION WHERE PARA BUSCAR QUE VARIABLES SON "LOROS" Y LE ASIGNA SU POSICION A UNA VARIABLE 
filtro_resultado = x[indices]    # VA A LA POSICION DE LOS ELEMENTOS EN LA VARIABLE QUE LOS CONTIENE Y SE LOS ASIGNA A OTRA VARIABLE 
print(filtro_resultado) 

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [75]:
# Crear una secuencia de 20 elementos
array_secuencia = np.arange(20)

# Transformar la secuencia en un array de 2 matrices de 5x2
array_matrices = array_secuencia.reshape(2, 5, 2) # ASIGNACION DE LOS DATOS DEL ARRAY A 2 "MATRICES DE 5 X 2" 
                                                   # RESHAPE TIENE LAS DIMENSIONES DE LA NUEVA ESTRUCTURA; FILAS, COLUMNAS, CANTIDAD (DE MATRICES) 
print(array_matrices)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [76]:
# Crear un array de 10 ceros
array = np.zeros(10) # LA FUNCION ZERO() CREA UN ARRAY DE CEROS DE LA DIMENSION QUE SE LE INDIQUE 

# Sustituir el cuarto elemento por 1
array[3] = 1 # 4º ELEMENTO 

# Imprimir el array por pantalla
print(array)

# Calcular el tamaño en memoria del array
tamaño_memoria = array.nbytes # LA FUNCION NBYTES() CALCULA EL TAMAÑO EN MEMORIA QUE OCUPA EN ESTE CASO LA VARIABLE "ARRAY"

print("El array ocupa", tamaño_memoria, "bytes en memoria.")

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
El array ocupa 80 bytes en memoria.


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [77]:
# Crear un vector que vaya del 10 al 49
vector = np.arange(10, 50)

# Invertir el vector
vector_invertido = np.flip(vector) # LA FUNCON FLIP() INVIERTE EN ESTE CASO A UN VECTOR 

# Imprimir el vector invertido por pantalla
print(vector_invertido)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [78]:
def indices_no_cero(vector): # DEVUELVE LAS POSICIONES DE LOS VALORES QUE NO SON "O"S DEL VECTOR 
    # Encontrar los índices de los valores que no sean cero
    indices = np.nonzero(vector)[0]
    return indices

# Vector dado
vector = np.array([1, 2, 0, 0, 4, 0])

# Llamar a la función y obtener los índices
resultado = indices_no_cero(vector)

print(resultado) 

[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [79]:
# Crear una matriz de números aleatorios 10x10
matriz = np.random.rand(10, 10)

# Encontrar el valor mínimo
minimo = np.min(matriz)

# Encontrar el valor máximo
maximo = np.max(matriz)

print("Valor mínimo:", minimo)
print("Valor máximo:", maximo) 

Valor mínimo: 0.002211982702705173
Valor máximo: 0.9587681260806983


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [80]:
# Crear un vector aleatorio de tamaño 30
vector = np.random.rand(30)

# Calcular la media del vector
media = np.mean(vector)

print("La media del vector aleatorio es:", media) 

La media del vector aleatorio es: 0.53168580987847


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [81]:
# Definir las dimensiones del array
filas = 5
columnas = 5

# Crear un array lleno de unos
array = np.ones((filas, columnas)) # LA FUNCION ONES() CREAR UN VECTOR DE 1 s 

# Actualizar el interior con ceros
array[1:-1, 1:-1] = 0 # SE LE ASIGNA EL VALOR "0" A LOS VALORES DE LA VARIABLE ARRAY EN EL RANGO QUE SE ESPECIFICA  

print(array) 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [92]:
# Crear una matriz de 8x8
matriz = np.zeros((8, 8), dtype=int) # A LA MATRIZ SE LE ASIGNAN SOLAMENTE VALORES = 0 

# Alternar entre 0s y 1s siguiendo el patrón dado
matriz[::2, 1::2] = 1 # DESDE LA PRIMERA POSICION EN EL EJE "Y" Y LA SEGUNDA POSICION EN EL EJE "X" SE INTERCALAN EN FILAS POR MEDIO Y POSICION POR MEDIO LOS NUMEROS "1"
'''[[0 1 0 1 0 1 0 1]
    [0 0 0 0 0 0 0 0]
    [0 1 0 1 0 1 0 1]
    [0 0 0 0 0 0 0 0]
    [0 1 0 1 0 1 0 1]
    [0 0 0 0 0 0 0 0]
    [0 1 0 1 0 1 0 1]
    [0 0 0 0 0 0 0 0]]'''
matriz[1::2, ::2] = 1 # DESDE LA SEGUNDA POSICION EN EL EJE "Y" Y LA PRIMERA POSICION EN EL EJE "X" SE INTERCALAN EN FILAS POR MEDIO Y POSICIONES POR MEDIO LOS NUMEROS "1"
'''[[0 0 0 0 0 0 0 0]
    [1 0 1 0 1 0 1 0]
    [0 0 0 0 0 0 0 0]
    [1 0 1 0 1 0 1 0]
    [0 0 0 0 0 0 0 0]
    [1 0 1 0 1 0 1 0]
    [0 0 0 0 0 0 0 0]
    [1 0 1 0 1 0 1 0]]'''
print(matriz) 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [87]:
# Definir la matriz base
matriz_base = np.array([[0, 1],
                        [1, 0]])

# Usar np.tile() para replicar la matriz base
matriz = np.tile(matriz_base, (4, 4)) # LA "FUNCION TILE()" RECIBE UNA MATRIZ BASE COMO PARAMETRO DE ENTRADA, Y LA REPITE LAS VECES QUE 
                                       # SE LE INDIQUE TANTO EN EL EJE Y COMO EN EL EJE X FORMANDO UNA NUEVA MATRIZ 
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [93]:
# Crear una matriz aleatoria de 5x5
matriz = np.random.rand(5, 5) # GENERA UNA MATRIZ DE FORMAS ESPECÍFICAS Y LA LLENA CON VALORES ALEATORIOS DISTRIBUIDOS UNIFORMEMENTE ENTRE 0 Y 1 

# Calcular la media y la desviación estándar de la matriz
media = np.mean(matriz)
desviacion_estandar = np.std(matriz)

# Normalizar la matriz
matriz_normalizada = (matriz - media) / desviacion_estandar

print("Matriz original:")
print(matriz)
print("\nMatriz normalizada:")
print(matriz_normalizada) 

Matriz original:
[[0.4569142  0.37655099 0.35460661 0.23247996 0.57436626]
 [0.92239638 0.0294834  0.69097568 0.66218099 0.80160822]
 [0.12173882 0.38123618 0.71471791 0.69460554 0.53431635]
 [0.68015784 0.8384034  0.70259166 0.25080984 0.63961131]
 [0.15525041 0.44843184 0.39601075 0.19918463 0.8662513 ]]

Matriz normalizada:
[[-0.21013024 -0.53437006 -0.62290863 -1.11565056  0.26375124]
 [ 1.66794135 -1.93467667  0.7342329   0.61805556  1.1805998 ]
 [-1.56245559 -0.51546683  0.8300252   0.74887823  0.10216265]
 [ 0.69058639  1.32905657  0.78109966 -1.04169537  0.52699413]
 [-1.42724707 -0.24435385 -0.45585617 -1.24998656  1.44141393]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [94]:
# Paso 1: Crear una secuencia de números del 0 al 10
secuencia = np.arange(11) # LA VARIABLE "SECUENCIA" ALMACENA UN DATO DEL TIPO ARREGLO QUE CONTIENE 11 NÚMEROS. 

# Paso 2: Crear un nuevo array que sustituya los valores entre 3 y 8 por -1
nuevo_array = np.where((secuencia >= 3) & (secuencia <= 8), -1, secuencia) # LA FUNCIÓN "WHERE()" BUSCA EN UNA VARIABLE QUE SE CUMPLAN LAS CONDICIONES INGRESADAS Y 
                                                                            # UNA VEZ IDENTIFICADOS DICHOS DATOS LOS OPERA SEGUN LO INDICADO 
# Paso 3: Crear un nuevo array que niegue los elementos entre 3 y 8
array_negado = np.where((secuencia >= 3) & (secuencia <= 8), ~secuencia, secuencia) # ~ ES UN OPERADOR QUE NIEGA EL NÚMERO ASIGNADO, ESPECIFICAMENTE CAMBIA SU SIGNO Y SU VALOR 

print("Secuencia original:")
print(secuencia)
print("\nNuevo array con elementos entre 3 y 8 sustituidos por -1:")
print(nuevo_array)
print("\nNuevo array que niega los elementos entre 3 y 8:")
print(array_negado)

Secuencia original:
[ 0  1  2  3  4  5  6  7  8  9 10]

Nuevo array con elementos entre 3 y 8 sustituidos por -1:
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]

Nuevo array que niega los elementos entre 3 y 8:
[ 0  1  2 -4 -5 -6 -7 -8 -9  9 10]
